# The influence of healthcare spending on life expectancy
## An essay by Frank Kloosterman & Jochem Vlug

![Healthcare](http://northcentralhealthdistrict.org/wp-content/uploads/2017/07/Coalition-banner.jpg)

In this report, a data analysis has been conducted on healthcare around the world. Using data from three datasets, we try to answer our research question:

*"What is the relation between life expectancy and healthcare spending?"*

This research question has two sub questions:
- Is there a relation between healthcare spending by government and life expectancy?
- Is there a relation between personal healthcare spending and life expactancy?
- Is there a relation between GDP and personal healthcare spending?

In [3]:
import pandas as pd #pandas, needed for data frames.
import numpy as np #numpy, for math operations and arrays.
import matplotlib.pyplot as plt #matplotlib, for making plots.
import missingno as msno #missingno, a usefull library for checking missing values.
import pdb #pythondebugger, native debugger of python.
%matplotlib inline 
#plots graphs directly below codeblocks.

In [4]:
#Worlddatabank on Social Development Goals
world_bank = pd.read_csv("data/SDG_csv/SDGData.csv") #TODO: URL MUST BE ONLINE
#Dataset on life expectancy, WHO
life_expectancy = pd.read_csv("data/life-expectancy.csv") #TODO: URL MUST BE ONLINE
#Dataset on household pocketmoney, NHA. Second row is empty, so we skip it.
household_ppp = pd.read_excel("data/NHA-indicators.xlsx",skiprows=[1],index_col=0) #TODO: URL MUST BE ONLINE

In [5]:
#Search world_bank database for keyphrase
def searchData(myInput):
    variableList = []
    for sentence in list(world_bank["Indicator Name"].values):
        newSentence = np.array(sentence.split(" "))
        for words in (newSentence):
            if words.lower() == myInput.lower(): 
                variableList += [sentence]

    variableList = pd.unique(variableList)
    return variableList
searchData("") #insert search input here.

array(['Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care  (% of women age 15-49)'],
      dtype=object)

In [ ]:
#First summarise status of data by making a NaN matrix.
msno.matrix(world_bank.sample(len(world_bank)))
msno.matrix(life_expectancy.sample(len(life_expectancy)))
msno.matrix(household_ppp.sample(len(household_ppp)))

In [6]:
#This function makes a Top 20 list of richest and poorest countries based on GDP per capita, PPP.
def findTop20():
    #Waarom doen we dit zo? Kunnen we niet gewoon world_bank["Country Name"].unique() nemen?
    countries = world_bank[world_bank["Indicator Name"]== 'GDP per capita, PPP (constant 2011 international $)']["Country Name"]
    GDP_2016 = world_bank[world_bank["Indicator Name"]== 'GDP per capita, PPP (constant 2011 international $)']["2016"]
    GDP_2017 = world_bank[world_bank["Indicator Name"]== 'GDP per capita, PPP (constant 2011 international $)']["2017"]

    GDP_1617 = countries.to_frame().join(GDP_2017.to_frame()).join(GDP_2016.to_frame())
    
    #Mask the entries in the top 20's of the list which are actually not countries.
    GDP_1617 = GDP_1617.mask(GDP_1617["Country Name"]=="Macao SAR, China")
    GDP_1617 = GDP_1617.mask(GDP_1617["Country Name"]=="Hong Kong SAR, China")
    GDP_1617 = GDP_1617.mask(GDP_1617["Country Name"]=="North America")
    #Masked San Marino as well, since almost no data available
    GDP_1617 = GDP_1617.mask(GDP_1617["Country Name"]=="San Marino")

    #Define the top20's
    lowest_20 = GDP_1617.sort_values("2017")[0:20]
    highest_20 = GDP_1617.sort_values("2017", ascending=False)[0:20]

    lowest_countries = lowest_20["Country Name"]
    highest_countries = highest_20["Country Name"]
    
    #Concate the highest and lowest together.
    newCountries = pd.concat([lowest_countries, highest_countries])
    #Changes the country names to match other database.
    #Tried to do this when merging databases, since Life_expectanc is also different
    #newCountries.iloc[3]="DRC"
    #newCountries.iloc[12]="Gambia"
    #newCountries.iloc[30]="United States of America"
    
    
    newCountries = newCountries.sort_values(ascending = True)
    
    #if, for some reason, the top 20 does not contain 20 entries, throw an error.
    if len(lowest_countries) < 19:
        return str("Something went wrong.")
    else:
        return list(newCountries.values)

In [35]:
#Using the top 20 richest and poorest countries, find matching data in other dataset.
def match_household(l):
    l[10]="DRC"
    l[13]="Gambia"
    l[39]="United States of America"
    newDF = household_ppp.loc[l]
    return newDF
#match_household(findTop20())

In [12]:
def match_LE(l):
    l[4]="Brunei"
    l[11] = "Congo"
    l[14] = "Gambia"
    #print(l)
    #print(life_expectancy["Entity"].unique())
    
    #print(life_expectancy)
    newDF = life_expectancy.loc[life_expectancy["Entity"].isin(l)]
    return newDF

#match_LE(findTop20())

In [34]:
#merge all the data in the same format ass the Household data in order to compare it. 
def transform_LE():
    LE_top20 = match_LE(findTop20())
    LE_afghanistan = LE_top20[LE_top20["Entity"]=="Afghanistan"]
    years = LE_afghanistan["Year"].values
    LE_afghanistan = LE_afghanistan.set_index(years)
    LE_afghanistan = LE_afghanistan.iloc[:,3:]
    LE_afghanistan.columns = ["Afghanistan"]
    LE_total = LE_afghanistan

    for Country in LE_top20["Entity"].unique():
        if Country not in LE_total.columns:
            LE_country = LE_top20[LE_top20["Entity"]==Country]
            years = LE_country["Year"].values
            LE_country = LE_country.set_index(years)
            LE_country = LE_country.iloc[:,3:]
            LE_country.columns = [Country]
            LE_total = pd.merge(LE_total, LE_country, left_index=True, right_index=True)
    LE_total = LE_total[50:]
    return(LE_total)

transform_LE()

,Afghanistan,Australia,Austria,Bahrain,Brunei,Burkina Faso,Burundi,Canada,Central African Republic,Chad,...,Rwanda,Saudi Arabia,Sierra Leone,Singapore,Sweden,Switzerland,Togo,Uganda,United Arab Emirates,United States
2000,55.481998,79.589996,78.238998,74.440002,75.202003,50.488998,51.544998,79.113998,43.937000,47.592999,...,48.415001,72.440002,38.702000,78.338997,79.724998,79.858002,53.488998,47.077000,74.238998,76.815002
2001,56.043999,79.885002,78.517998,74.635002,75.425003,50.893002,51.778999,79.337997,43.755001,47.603001,...,49.792999,72.651001,39.660000,78.664001,79.893997,80.117996,53.550999,48.119999,74.487000,76.962997
2002,56.637001,80.175003,78.791000,74.821999,75.650002,51.383999,51.977001,79.565002,43.717999,47.638000,...,50.970001,72.820000,40.660000,79.028999,80.061996,80.377998,53.707001,49.242001,74.730003,77.121002
2003,57.250000,80.452003,79.058998,74.999001,75.875000,51.956001,52.189999,79.791000,43.827000,47.716000,...,52.268002,72.947998,41.668999,79.419998,80.235001,80.640999,53.935001,50.394001,74.968002,77.292000
2004,57.875000,80.712997,79.318001,75.167000,76.093002,52.602001,52.437000,80.013000,44.080002,47.848000,...,53.755001,73.041000,42.660000,79.824997,80.413002,80.903999,54.230000,51.537998,75.199997,77.474998
2005,58.500000,80.955002,79.566002,75.325996,76.291000,53.310001,52.735001,80.232002,44.466000,48.054001,...,55.430000,73.112000,43.624001,80.230003,80.596001,81.163002,54.598000,52.639999,75.421997,77.667000
2006,59.110001,81.175003,79.799004,75.477997,76.455002,54.063000,53.090000,80.446999,44.966999,48.348999,...,57.219002,73.176003,44.566002,80.619003,80.780998,81.413002,55.048000,53.681000,75.632004,77.859001
2007,59.694000,81.376999,80.015999,75.625000,76.577003,54.841000,53.492001,80.658997,45.551998,48.729000,...,58.971001,73.245003,45.500000,80.982002,80.963997,81.650002,55.577999,54.660000,75.828003,78.045998
2008,60.243000,81.565002,80.218002,75.769997,76.655998,55.618000,53.925999,80.870003,46.189999,49.181999,...,60.564999,73.331001,46.431999,81.311996,81.142998,81.872002,56.174000,55.574001,76.012001,78.223000
2009,60.754002,81.741997,80.406998,75.913002,76.698997,56.375999,54.386002,81.079002,46.862000,49.691002,...,61.962002,73.440002,47.348000,81.602997,81.317001,82.078003,56.813999,56.409000,76.182999,78.387001
2010,61.226002,81.910004,80.584000,76.056000,76.719002,57.096001,54.861000,81.283997,47.560001,50.233002,...,63.139999,73.573997,48.223999,81.856003,81.486000,82.269997,57.465000,57.153000,76.344002,78.539001
2011,61.666000,82.072998,80.752998,76.198997,76.734001,57.762001,55.338001,81.482002,48.284000,50.778000,...,64.106003,73.730003,49.034000,82.078003,81.650002,82.449997,58.091999,57.796001,76.498001,78.681999
2012,62.085999,82.234001,80.917999,76.341003,76.764000,58.376999,55.806999,81.674004,49.041000,51.299999,...,64.911003,73.896004,49.762001,82.279999,81.813004,82.625000,58.667999,58.347000,76.648003,78.820999
2013,62.493999,82.394997,81.083000,76.482002,76.822998,58.942001,56.258999,81.858002,49.825001,51.778000,...,65.598000,74.066002,50.401001,82.473000,81.974998,82.796997,59.174000,58.819000,76.797997,78.959999
2014,62.895000,82.558998,81.250000,76.622002,76.917000,59.457001,56.688000,82.035004,50.620998,52.203999,...,66.188004,74.234001,50.951000,82.662003,82.136002,82.968002,59.601002,59.223999,76.947998,79.099998
2015,63.287998,82.725998,81.419998,76.761002,77.045998,59.926998,57.094002,82.206001,51.410000,52.575001,...,66.695999,74.400002,51.423000,82.848999,82.299004,83.139000,59.949001,59.575001,77.100998,79.244003